name: breakpoints
description: A simple library for getting page breakpoints xs, sm, md, lg, xl
version: 0.2.0
homepage: https://github.com/januwA/flutter_breakpoints

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  test: ^1.0.0
